export function getUi() {
  const ui = {
    app: document.getElementById("app"),
    editorPanel: document.getElementById("editorPanel"),
    backdrop: document.getElementById("panelBackdrop"),
    cards: document.getElementById("cardsContainer"),
    count: document.getElementById("questionCountLabel"),
    selectedCount: document.getElementById("selectedCountLabel"),
    status: document.getElementById("statusMessage"),
    statusLog: document.getElementById("statusLog"),
    toastStack: document.getElementById("toastStack"),
    saveStatePill: document.getElementById("saveStatePill"),
    commandPaletteBtn: document.getElementById("commandPaletteBtn"),
    openJsonToolsBtn: document.getElementById("openJsonToolsBtn"),
    openControlsBtn: document.getElementById("openControlsBtn"),
    themeToggleBtn: document.getElementById("themeToggleBtn"),
    contrastToggleBtn: document.getElementById("contrastToggleBtn"),
    shortcutsBtn: document.getElementById("shortcutsBtn"),
    closeControlsBtn: document.getElementById("closeControlsBtn"),
    closeEditorBtn: document.getElementById("closeEditorBtn"),
    undoBtn: document.getElementById("undoBtn"),
    redoBtn: document.getElementById("redoBtn"),
    addQuestionBtn: document.getElementById("addQuestionBtn"),
    deleteQuestionBtn: document.getElementById("deleteQuestionBtn"),
    deleteSelectedBtn: document.getElementById("deleteSelectedBtn"),
    assignTagBtn: document.getElementById("assignTagBtn"),
    cloneSelectedBtn: document.getElementById("cloneSelectedBtn"),
    shuffleSelectedBtn: document.getElementById("shuffleSelectedBtn"),
    importJsonBtn: document.getElementById("importJsonBtn"),
    importJsonInput: document.getElementById("importJsonInput"),
    openExamSettingsBtn: document.getElementById("openExamSettingsBtn"),
    exportSelectedBtn: document.getElementById("exportSelectedBtn"),
    exportJsonBtn: document.getElementById("exportJsonBtn"),
    exportAnswerKeyBtn: document.getElementById("exportAnswerKeyBtn"),
    printQuestionsBtn: document.getElementById("printQuestionsBtn"),
    printAnswerKeyBtn: document.getElementById("printAnswerKeyBtn"),
    openTestHarnessBtn: document.getElementById("openTestHarnessBtn"),
    examPresetSelect: document.getElementById("examPresetSelect"),
    securityFullscreenToggle: document.getElementById("securityFullscreenToggle"),
    securityNavWarnToggle: document.getElementById("securityNavWarnToggle"),
    securityTokenToggle: document.getElementById("securityTokenToggle"),
    institutionInput: document.getElementById("institutionInput"),
    subjectInput: document.getElementById("subjectInput"),
    examCodeInput: document.getElementById("examCodeInput"),
    negativeMarksInput: document.getElementById("negativeMarksInput"),
    studentInfoToggle: document.getElementById("studentInfoToggle"),
    saveSnapshotBtn: document.getElementById("saveSnapshotBtn"),
    snapshotLibraryBtn: document.getElementById("snapshotLibraryBtn"),
    questionSearchInput: document.getElementById("questionSearchInput"),
    topicFilterSelect: document.getElementById("topicFilterSelect"),
    difficultyFilterSelect: document.getElementById("difficultyFilterSelect"),
    showDuplicatesToggle: document.getElementById("showDuplicatesToggle"),
    statsGrid: document.getElementById("statsGrid"),
    openExamSettingsEditorBtn: document.getElementById("openExamSettingsEditorBtn"),
    openQuestionDetailsBtn: document.getElementById("openQuestionDetailsBtn"),
    createExamBtn: document.getElementById("createExamBtn"),
    form: document.getElementById("editorForm"),
    editorScroll: document.querySelector("#editorPanel .editor-scroll"),
    questionInput: document.getElementById("questionInput"),
    topicInput: document.getElementById("topicInput"),
    difficultySelect: document.getElementById("difficultySelect"),
    marksInput: document.getElementById("marksInput"),
    tagsInput: document.getElementById("tagsInput"),
    explanationInput: document.getElementById("explanationInput"),
    questionMathPreview: document.getElementById("questionMathPreview"),
    questionMathHint: document.getElementById("questionMathHint"),
    optionToolbar: document.getElementById("optionToolbar"),
    optionMoveUpBtn: document.getElementById("optionMoveUpBtn"),
    optionMoveDownBtn: document.getElementById("optionMoveDownBtn"),
    optionToolbarHint: document.getElementById("optionToolbarHint"),
    optionList: document.getElementById("optionList"),
    addOptionBtn: document.getElementById("addOptionBtn"),
    cancelBtn: document.getElementById("cancelEditBtn"),
    editorFloatBackdrop: document.getElementById("editorFloatBackdrop"),
    questionFloatCard: document.getElementById("questionFloatCard"),
    questionFloatBody: document.getElementById("questionFloatBody"),
    questionFloatInputMount: document.getElementById("questionFloatInputMount"),
    questionFloatPreview: document.getElementById("questionFloatPreview"),
    floatOpenStructuresBtn: document.getElementById("floatOpenStructuresBtn"),
    floatOpenSymbolsBtn: document.getElementById("floatOpenSymbolsBtn"),
    floatCloseQuestionBtn: document.getElementById("floatCloseQuestionBtn"),
    floatSaveQuestionBtn: document.getElementById("floatSaveQuestionBtn"),
    floatCancelQuestionBtn: document.getElementById("floatCancelQuestionBtn"),
    floatOptionMoveUpBtn: document.getElementById("floatOptionMoveUpBtn"),
    floatOptionMoveDownBtn: document.getElementById("floatOptionMoveDownBtn"),
    floatOptionDeleteBtn: document.getElementById("floatOptionDeleteBtn"),
    optionEditFloatCard: document.getElementById("optionEditFloatCard"),
    optionEditFloatBody: document.getElementById("optionEditFloatBody"),
    optionEditFloatInputMount: document.getElementById("optionEditFloatInputMount"),
    optionFloatPreview: document.getElementById("optionFloatPreview"),
    floatOptionMathHoldBtn: document.getElementById("floatOptionMathHoldBtn"),
    floatOptionMathTargets: document.getElementById("floatOptionMathTargets"),
    floatOptionMathSymbolsTarget: document.getElementById("floatOptionMathSymbolsTarget"),
    floatOptionMathStructuresTarget: document.getElementById("floatOptionMathStructuresTarget"),
    floatOptionOpenStructuresBtn: document.getElementById("floatOptionOpenStructuresBtn"),
    floatOptionOpenSymbolsBtn: document.getElementById("floatOptionOpenSymbolsBtn"),
    floatCloseOptionEditBtn: document.getElementById("floatCloseOptionEditBtn"),
    floatSaveOptionEditBtn: document.getElementById("floatSaveOptionEditBtn"),
    floatCancelOptionEditBtn: document.getElementById("floatCancelOptionEditBtn"),
    mathNavSection: document.getElementById("mathNavSection"),
    mathSearchInput: document.getElementById("mathSearchInput"),
    mathStructuresTab: document.getElementById("mathStructuresTab"),
    mathSymbolsTab: document.getElementById("mathSymbolsTab"),
    mathStructuresPanel: document.getElementById("mathStructuresPanel"),
    mathSymbolsPanel: document.getElementById("mathSymbolsPanel"),
    importReportModal: document.getElementById("importReportModal"),
    closeImportReportBtn: document.getElementById("closeImportReportBtn"),
    importReportContent: document.getElementById("importReportContent"),
    preflightModal: document.getElementById("preflightModal"),
    closePreflightBtn: document.getElementById("closePreflightBtn"),
    preflightContent: document.getElementById("preflightContent"),
    continuePreflightBtn: document.getElementById("continuePreflightBtn"),
    cancelPreflightBtn: document.getElementById("cancelPreflightBtn"),
    shortcutsModal: document.getElementById("shortcutsModal"),
    closeShortcutsBtn: document.getElementById("closeShortcutsBtn"),
    shortcutsContent: document.getElementById("shortcutsContent"),
    jsonToolsModal: document.getElementById("jsonToolsModal"),
    closeJsonToolsBtn: document.getElementById("closeJsonToolsBtn"),
    cancelJsonToolsBtn: document.getElementById("cancelJsonToolsBtn"),
    mathToolsModal: document.getElementById("mathToolsModal"),
    closeMathToolsBtn: document.getElementById("closeMathToolsBtn"),
    questionDetailsModal: document.getElementById("questionDetailsModal"),
    closeQuestionDetailsBtn: document.getElementById("closeQuestionDetailsBtn"),
    saveQuestionDetailsBtn: document.getElementById("saveQuestionDetailsBtn"),
    cancelQuestionDetailsBtn: document.getElementById("cancelQuestionDetailsBtn"),
    examSettingsModal: document.getElementById("examSettingsModal"),
    closeExamSettingsBtn: document.getElementById("closeExamSettingsBtn"),
    cancelExamSettingsBtn: document.getElementById("cancelExamSettingsBtn"),
    commandPaletteModal: document.getElementById("commandPaletteModal"),
    closeCommandPaletteBtn: document.getElementById("closeCommandPaletteBtn"),
    commandPaletteInput: document.getElementById("commandPaletteInput"),
    commandPaletteList: document.getElementById("commandPaletteList"),
    snapshotModal: document.getElementById("snapshotModal"),
    closeSnapshotBtn: document.getElementById("closeSnapshotBtn"),
    snapshotContent: document.getElementById("snapshotContent")
  };

  const requiredUiKeys = [
    "app",
    "editorPanel",
    "backdrop",
    "cards",
    "count",
    "selectedCount",
    "status",
    "statusLog",
    "toastStack",
    "saveStatePill",
    "commandPaletteBtn",
    "openJsonToolsBtn",
    "openControlsBtn",
    "themeToggleBtn",
    "contrastToggleBtn",
    "shortcutsBtn",
    "closeControlsBtn",
    "closeEditorBtn",
    "undoBtn",
    "redoBtn",
    "addQuestionBtn",
    "deleteQuestionBtn",
    "deleteSelectedBtn",
    "assignTagBtn",
    "cloneSelectedBtn",
    "shuffleSelectedBtn",
    "importJsonBtn",
    "importJsonInput",
    "openExamSettingsBtn",
    "exportSelectedBtn",
    "exportJsonBtn",
    "exportAnswerKeyBtn",
    "printQuestionsBtn",
    "printAnswerKeyBtn",
    "openTestHarnessBtn",
    "examPresetSelect",
    "securityFullscreenToggle",
    "securityNavWarnToggle",
    "securityTokenToggle",
    "institutionInput",
    "subjectInput",
    "examCodeInput",
    "negativeMarksInput",
    "studentInfoToggle",
    "saveSnapshotBtn",
    "snapshotLibraryBtn",
    "questionSearchInput",
    "topicFilterSelect",
    "difficultyFilterSelect",
    "showDuplicatesToggle",
    "statsGrid",
    "openExamSettingsEditorBtn",
    "openQuestionDetailsBtn",
    "createExamBtn",
    "form",
    "questionInput",
    "topicInput",
    "difficultySelect",
    "marksInput",
    "tagsInput",
    "explanationInput",
    "questionMathPreview",
    "optionToolbar",
    "optionMoveUpBtn",
    "optionMoveDownBtn",
    "optionToolbarHint",
    "optionList",
    "addOptionBtn",
    "cancelBtn",
    "editorScroll",
    "editorFloatBackdrop",
    "questionFloatCard",
    "questionFloatBody",
    "questionFloatInputMount",
    "questionFloatPreview",
    "floatCloseQuestionBtn",
    "floatSaveQuestionBtn",
    "floatCancelQuestionBtn",
    "floatOptionMoveUpBtn",
    "floatOptionMoveDownBtn",
    "floatOptionDeleteBtn",
    "optionEditFloatCard",
    "optionEditFloatBody",
    "optionEditFloatInputMount",
    "optionFloatPreview",
    "floatOptionMathHoldBtn",
    "floatOptionMathTargets",
    "floatOptionMathSymbolsTarget",
    "floatOptionMathStructuresTarget",
    "floatOptionOpenStructuresBtn",
    "floatOptionOpenSymbolsBtn",
    "floatCloseOptionEditBtn",
    "floatSaveOptionEditBtn",
    "floatCancelOptionEditBtn",
    "mathNavSection",
    "mathStructuresTab",
    "mathSymbolsTab",
    "mathStructuresPanel",
    "mathSymbolsPanel",
    "importReportModal",
    "closeImportReportBtn",
    "importReportContent",
    "preflightModal",
    "closePreflightBtn",
    "preflightContent",
    "continuePreflightBtn",
    "cancelPreflightBtn",
    "shortcutsModal",
    "closeShortcutsBtn",
    "shortcutsContent",
    "jsonToolsModal",
    "closeJsonToolsBtn",
    "cancelJsonToolsBtn",
    "mathToolsModal",
    "closeMathToolsBtn",
    "questionDetailsModal",
    "closeQuestionDetailsBtn",
    "saveQuestionDetailsBtn",
    "cancelQuestionDetailsBtn",
    "examSettingsModal",
    "closeExamSettingsBtn",
    "cancelExamSettingsBtn",
    "commandPaletteModal",
    "closeCommandPaletteBtn",
    "commandPaletteInput",
    "commandPaletteList",
    "snapshotModal",
    "closeSnapshotBtn",
    "snapshotContent"
  ];

  const missingUi = requiredUiKeys.filter((key) => !ui[key]);
  if (missingUi.length > 0) {
    throw new Error("MCQAdminPanel bootstrap failed. Missing UI elements: " + missingUi.join(", "));
  }

  // Optional enhancement nodes: create safe fallbacks if markup is older.
  if (!ui.mathSearchInput) {
    const fallbackSearch = document.createElement("input");
    fallbackSearch.type = "text";
    fallbackSearch.id = "mathSearchInput";
    fallbackSearch.className = "math-search-input";
    fallbackSearch.placeholder = "Search structures and symbols (Ctrl/Cmd+K)";
    fallbackSearch.setAttribute("aria-label", "Search math structures and symbols");

    const wrap = document.createElement("div");
    wrap.className = "math-search-wrap";
    wrap.appendChild(fallbackSearch);
    ui.mathNavSection.prepend(wrap);
    ui.mathSearchInput = fallbackSearch;
  }

  if (!ui.questionMathHint) {
    const fallbackHint = document.createElement("p");
    fallbackHint.id = "questionMathHint";
    fallbackHint.className = "math-hint";
    fallbackHint.setAttribute("aria-live", "polite");
    ui.questionMathPreview.insertAdjacentElement("afterend", fallbackHint);
    ui.questionMathHint = fallbackHint;
  }

  return ui;
}
